apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: acrname.azurecr.io/apptest1:tag
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
  - port: 80
    targetPort: 5001

